name: TheWhalezazaLib
version: ${project.version}
main: me.thewhalezaza.thewhalezazalib.TWZLibraly
api-version: 1.16
authors: [ TheWhalezaza ]
description: TWZLibraly

commands:
  tlib:
    usage: /tlib
